name: Test build wheel

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.python }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      matrix:
        # From wheel.yml of numpy (https://github.com/numpy/numpy/blob/main/.github/workflows/wheels.yml):
        # Github Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        buildplat:
        # macos-15-intel is an Intel runner, macos-14 is Apple silicon
          - [ubuntu-latest, manylinux_x86_64]
          - [ubuntu-latest, musllinux_x86_64]
          - [ubuntu-24.04-arm, manylinux_aarch64]
          - [ubuntu-24.04-arm, musllinux_aarch64]
          - [macos-15-intel, macosx_x86_64]
          - [macos-14, macosx_arm64]
          - [windows-latest, win_amd64]
          - [windows-2022, win32]
          - [windows-11-arm, win_arm64]
        python: ["cp38", "cp39", "cp310", "cp311", "cp312", "cp313", "cp314", "pp39"]
        exclude:
          - buildplat: [windows-latest, win_amd64]
            python: "pp39"
          - buildplat: [windows-2022, win32]
            python: "pp39"
          - buildplat: [windows-11-arm, win_arm64]
            python: "pp39"
          - buildplat: [ ubuntu-latest, musllinux_x86_64 ]
            python: "pp39"
          - buildplat: [ ubuntu-24.04-arm, musllinux_aarch64 ]
            python: "pp39"
          - buildplat: [windows-11-arm, win_arm64]
            python: "cp38"
    env:
      CIBW_ENABLE: "pypy"

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set up QEMU
        if: ${{ contains(matrix.buildplat[1], 'linux_aarch64') }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Setup MSVC (32-bit)
        if: ${{ matrix.buildplat[1] == 'win32' }}
        uses: bus1/cabuild/action/msdevshell@e22aba57d6e74891d059d66501b6b5aed8123c4d  # v1
        with:
          architecture: 'x86'

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.1
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
          CIBW_ENVIRONMENT: "MACOSX_DEPLOYMENT_TARGET=11.0"

      - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: tmp-sdist
          path: dist/*.tar.gz
